# Generated by Django 5.2.4 on 2025-07-14 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Frase motivacional')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Frase Motivacional',
                'verbose_name_plural': 'Frases Motivacionais',
            },
        ),
        migrations.CreateModel(
            name='CheckinEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.CharField(max_length=50, verbose_name='Humor do usuário')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do check-in')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Check-in do usuário')),
            ],
            options={
                'verbose_name': 'Check-in Emocional',
                'verbose_name_plural': 'Check-ins Emocionais',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do diário')),
                ('humor', models.CharField(blank=True, max_length=20, verbose_name='Humor do dia')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diário do usuário')),
            ],
            options={
                'verbose_name': 'Registro de Diário',
                'verbose_name_plural': 'Registros de Diário',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Conteúdo da mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MensagemPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Conteúdo da mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas_privadas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas_privadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem Privada',
                'verbose_name_plural': 'Mensagens Privadas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MetaTerapeutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da meta')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_progresso', 'Em Progresso'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status da meta')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Meta para o usuário')),
            ],
            options={
                'verbose_name': 'Meta Terapêutica',
                'verbose_name_plural': 'Metas Terapêuticas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paciente', 'Paciente'), ('psicologo', 'Psicólogo')], default='paciente', max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do psicólogo')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do psicólogo')),
                ('registro_crp', models.CharField(max_length=20, verbose_name='Registro CRP')),
                ('especialidades', models.TextField(blank=True, verbose_name='Especialidades')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_psicologo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
        migrations.CreateModel(
            name='ConexaoPsicologoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conexao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo_responsavel', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_atribuidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão Psicólogo-Paciente',
                'verbose_name_plural': 'Conexões Psicólogo-Paciente',
                'unique_together': {('psicologo', 'paciente')},
            },
        ),
    ]
